### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by manodhiambo**
More updates on the readme file

### CODE REVIEW

**Review by ABDULALI3468 — CHANGES_REQUESTED** [review]
# Changes Required 👍 

Hi @manodhiambo , 



Indeed you did an exceptional but still, there is room for changes to complete this project. 💯

 ## Required Changes ♻️

**1-** Please consider always using the name of your feature branch as a way to highlight what you did in it (e.g. 'created_sidebar' or 'added_comments_section')  In this case, your branch name is `manodhiambo-patch-1` which is not professional.

> Consider checking out from your current branch to a new branch and for this case, you can name it `feature-1/setup-basic-repo-configurations` or something else that describes what you did in the branch. Remember in the new PR which you will open for another review add the link of this PR in that PR's Description.


**2-** Please consider adding a professional title and description of your PR which describes what you have done in the Pull Request (PR). In this case, it's not describing it clearly.

>   pull_request_desc

**3-** Please consider setting up Linters to your repository as it helps find issues that can lead to bugs or inconsistencies with code health and style to make your code base and repository look professional.

### [Linters setup](https://github.com/microverseinc/linters-config/tree/master/html-css).

**4-** - It's a project requirement to add a `test.md file` and `node-modules directory` in the `.gitignore file`. Currently, the `.gitignore file` only has `test.md`, and still, the `test.md` is on GitHub and not ignored by Git. Consider reviewing it.      

image

**5-** In the case of README consider not leaving any of the sections in the [Microverse README](https://github.com/microverseinc/readme-template) template as it's a project requirement. But please consider adding the content to it in accordance with your repository. Like the tech stack needs to be one you used like Html, and CSS, the Getting started guide needs to have details regarding your repo. Also, consider giving acknowledgments, etc, and don't forget to connect the MIT license file in README.

- The only optional section is FAQ.
- You can delete the live demo section if there is no deployment of the project on some server. In this case please consider deleting that section.
- Make sure the to add section Future Features, including 1-3 potential features to be added.



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: GitHub followers
> * This is My **Linkedin**: [Linkedin Badge](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [Twitter Badge](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by GedeonTS — COMMENTED** [review]
# STATUS: CHANGES REQUIRED :recycle: :
Hi @manodhiambo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.



 ## Highlights :tophat: :+1: 
- No linter errors :+1: 

 ## Required Changes ♻️
- [ ] Kindly make sure to submit an open Pull request which implies having a branch that hasn't been deleted yet. :recycle: 
- [ ] As requested by the previous reviewer :recycle: ,indly make sure to write a more descriptive PR summary by describing every step you went on to complete this milestone :recycle: 
- [ ]  As requested by the previous reviewer too, Kindly make sure to add a professional README file following this [template](https://github.com/microverseinc/readme-template) provided by microverse :recycle: 


## Optional suggestions :ringed_planet: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tsohleDev** [comment]
Hi Micronaut 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### 🔴 Please make sure that your branch exist

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by bobb-Rob — COMMENTED** [review]
## STATUS: CHANGES REQUIRED ♻️
Hi @manodhiambo, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Required Changes ♻️

- [ ] The branch [manodhiambo-patch-1](https://github.com/manodhiambo/Microverse_Project/tree/manodhiambo-patch-1) leads to a `404` page meaning that this branch does not exist. Therefore, I am unable to verify your README file and other project requirement. 
- [ ] Please ensure that you create a new branch using the correct naming convention as suggested by the [previous reviewer](https://github.com/manodhiambo/Microverse_Project/pull/1#pullrequestreview-1354256955). Thereafter, open a new pull request with proper title and description. 
- [ ] Please slowly go through all issues raised by previous reviewers and fix the issues. In case where you are not satisfied with the comments, you can reach out to an of us.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
